### ISSUE TITLE
CSS Gradients (Farbverläufe)

### ISSUE THREAD

**Issue by oelna** [oelna/hsma-html#82]
https://www.youtube.com/watch?v=f3mwKLXpOLk

**Comment by oelna** [comment]
```css
@keyframes sponsors-progress-animation {
	0% {
		background-position: 100%
	}

	to {
		background-position: 0
	}
}
```

```css
.x {
	animation: sponsors-progress-animation 2s linear infinite;
	background: linear-gradient(90deg,#ffd33d,#ea4aaa 17%,#b34bff 34%,#01feff 51%,#ffd33d 68%,#ea4aaa 85%,#b34bff);
	background-size: 300% 100%;
	cursor: pointer;
}
```

from https://github.com/sponsors/willmcgugan
